### ISSUE TITLE
host, owner and repository should be dynamic

### ISSUE THREAD

**Issue by robertkowalski** [joyent/git-apply-pr#2]
so we can use it for the website :)

**Comment by tjfontaine** [comment]
absolutely, some thoughts I had on this would be: `git apply-pr joyent/node#12345` which we could then parse and know where we were looking

**Comment by robertkowalski** [comment]
sounds good, i can probably take care of that this we

**Comment by robertkowalski** [comment]
/(\w_)\/(\w_)#(\d*)/.exec("joyent/node#1337")
